url: https://burnsideautomotive.github.io
baseurl: https://burnsideautomotive.github.io/

# Site settings
title: Burnside Automotive
email: burnsideautomotive@gmail.com
description: "Burnside Automotive is a garage and workshop in Green Island, Dunedin. We do car repairs, upgrades, warrant of fitness (WOF) and general servicing."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: BA0B0B
  secondary: 970808
  secondary-dark: 055A5A

# Team names, titles and social links
people:
- name: Brett Reid
  pic: 1
  position: Lead Meachic / Owner
  social:
    - title: facebook
      url: facebook.com/burnsideautomotive

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: facebook.com/burnsideautomotive

# Postal address (add as many lines as necessary)
address:
  - line: 109 Main South Rd
  - line: Burnside, Dunedin 9018

# Build settings
markdown: kramdown
permalink: pretty
