url: https://burnsideautomotive.github.io
baseurl: /

# Site settings
title: Burnside Automotive
email: burnsideautomotive@gmail.com
description: "Burnside Automotive is a garage and workshop in Green Island, Dunedin. We do car repairs, upgrades, warrant of fitness (WOF) and general servicing."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Brett Reid
  pic: 1
  position: Lead Meachic / Owner
  social:
    - title: facebook
      url: facebook.com/burnsideautomotive

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
