url: https://burnsideautomotive.github.io
baseurl: C:/Projects/burnsideautomotive/_site/

# Site settings
title: Burnside Automotive
email: burnsideautomotive@gmail.com
description: "Burnside Automotive is a garage and workshop in Green Island, Dunedin. We do car repairs, upgrades, warrant of fitness (WOF) and general servicing."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: BA0B0B
  secondary: 970808
  secondary-dark: 055A5A

# Team names, titles and social links
people:
- name: Brett Reid
  pic: 1
  position: Lead Meachic / Owner
  social:
    - title: facebook
      url: facebook.com/burnsideautomotive

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

mapping:
    provider: google_js
    api_key: AIzaSyDID3zqV3aVuvKTinlKYpRNrirntkohz70
    zoom: 10
    dimensions:
      width: 600
      height: 400
    latitude: -45.9021512
    longitude: 170.4421913

